language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - pypy
  - pypy3
env:
  matrix:
    - SELENIUM_WEBDRIVER=default
    - SELENIUM_WEBDRIVER=chrome
matrix:
  fast_finish: true
install:
  - pip install -e .
  - pip install -e git+https://github.com/ocadotechnology/codeforlife-portal.git#egg=codeforlife-portal #TODO: Remove as part of #688
  - pip install coveralls
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
script:
  - python setup.py test
after_success:
  - coveralls
