language: python
python:
- 2.7
- 3.3
- 3.4
- 3.5
- pypy
- pypy3
matrix:
  fast_finish: true
install:
- pip install -e .
- pip install git+https://github.com/ocadotechnology/codeforlife-portal.git#egg=codeforlife-portal #TODO: Remove as part of #688
- pip install coveralls
script:
- python setup.py test
after_success:
- coveralls
