language: python
python:
  - 2.7
env:
  matrix:
    - SELENIUM_WEBDRIVER=default
matrix:
  allow_failures:
    - python: 3.3
      env: SELENIUM_WEBDRIVER=default
    - python: 3.4
      env: SELENIUM_WEBDRIVER=default
    - python: 3.5
      env: SELENIUM_WEBDRIVER=default
    - python: pypy
      env: SELENIUM_WEBDRIVER=default
    - python: pypy3
      env: SELENIUM_WEBDRIVER=default
  include:
    - python: 3.3
      env: SELENIUM_WEBDRIVER=default
    - python: 3.4
      env: SELENIUM_WEBDRIVER=default
    - python: 3.5
      env: SELENIUM_WEBDRIVER=default
    - python: pypy
      env: SELENIUM_WEBDRIVER=default
    - python: pypy3
      env: SELENIUM_WEBDRIVER=default
  fast_finish: true
before_install:
  - gem install sass
install:
  - pip install -e .
  - pip install -e git+https://github.com/ocadotechnology/codeforlife-portal.git#egg=codeforlife-portal #TODO: Remove as part of #688
  - pip install coveralls
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
script:
  - python setup.py test
after_success:
  - coveralls
