#!/bin/bash
set -e
cd "${BASH_SOURCE%/*}"

pip install -e .
./example_project/manage.py migrate --noinput

cd game
django-admin compilemessages
cd -

./example_project/manage.py collectstatic --noinput
./example_project/manage.py runserver "$@"
